### ISSUE TITLE
No code hinting due to missing vendor directory

### ISSUE THREAD

**Issue by ebuzzz** [codemix/yii2-dockerbase#7]
Because of the way this image works with the yii2-dockerized image, these images cannot be used for real development work. This is because the vendor folder is not available for the host, that has the actual source code.

I've been thinking about changing the vendor directory back to the normal situation, and copy the contents of /var/www/vendor into the document root when the container is created. Am I missing some fundemental problems on why this won't work on the long run?

**Comment by mikehaertl** [comment]
If the question is, why the vendor directory is outside the project folder, see here:
https://github.com/codemix/yii2-dockerized/wiki/7.-FAQ#where-are-composer-packages-installed

To get the vendor directory back on the host, I usually do this, each time I update the vendor directory inside the image:

https://github.com/codemix/yii2-dockerized/wiki/7.-FAQ#how-can-i-make-composer-packages-available-locally

**Comment by mikehaertl** [comment]
BTW the `yii2-dockerbase` image will go away soon. I've refactored the `yii2-dockerized` in such a way, that you'll always build your own base image there.

You can have a look at this on the dev branch:
https://github.com/codemix/yii2-dockerized/tree/dev

But it still will have the vendor directory outside the project, because I want all dependencies in `vendor` to be part of my image and still be able to map the local app directory into the container, without overwriting `vendor` there.

**Comment by ebuzzz** [comment]
Didn't notice there was an active wiki btw, sorry.
Too bad Docker can't symlink something 'over' the mapped volume. Copying seems the only way to go then.

Dev version looks good. It also remedies the problem I had with different Yii version requirements. So this looks much cleaner. Any idea when dev will be production ready?

**Comment by mikehaertl** [comment]
@eborned I'd say it already is. I think I wanted to tidy it up a little more, but basically it should be usable. 

So closing this for now as there's nothing to fix really.
